// <auto-generated />
using System;
using EmployeeManagement.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EmployeeManagement.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EmployeeManagement.Models.Employee", b =>
                {
                    b.Property<string>("EmployeeId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("HireDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Salary")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EmployeeId");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            EmployeeId = "EM001",
                            Address = "123 Main St, City, Country",
                            Department = "HR",
                            Email = "john.carter@company.com",
                            Gender = "Male",
                            HireDate = new DateTime(2020, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "John Carter",
                            PhoneNumber = "1234567890",
                            Position = "HR Manager",
                            Role = "Admin",
                            Salary = 3000m,
                            Status = "Active"
                        },
                        new
                        {
                            EmployeeId = "EM002",
                            Address = "123 Main St, City, Country",
                            Department = "SC",
                            Email = "michael.bean@company.com",
                            Gender = "Male",
                            HireDate = new DateTime(2021, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Michael Bean",
                            PhoneNumber = "2345678901",
                            Position = "Supply Chain Specialist",
                            Role = "Employee",
                            Salary = 1300m,
                            Status = "Active"
                        },
                        new
                        {
                            EmployeeId = "EM003",
                            Address = "123 Main St, City, Country",
                            Department = "MD",
                            Email = "jimmy.floy@company.com",
                            Gender = "Male",
                            HireDate = new DateTime(2019, 5, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Jimmy Floy",
                            PhoneNumber = "3456789012",
                            Position = "Medical Doctor",
                            Role = "Employee",
                            Salary = 2000m,
                            Status = "Active"
                        },
                        new
                        {
                            EmployeeId = "EM004",
                            Address = "123 Main St, City, Country",
                            Department = "MD",
                            Email = "mary.brown@company.com",
                            Gender = "Female",
                            HireDate = new DateTime(2020, 7, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Mary Brown",
                            PhoneNumber = "4567890123",
                            Position = "Medical Doctor",
                            Role = "Employee",
                            Salary = 2000m,
                            Status = "Active"
                        },
                        new
                        {
                            EmployeeId = "EM005",
                            Address = "123 Main St, City, Country",
                            Department = "HR",
                            Email = "duc.tran@company.com",
                            Gender = "Male",
                            HireDate = new DateTime(2018, 9, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Duc Tran",
                            PhoneNumber = "5678901234",
                            Position = "HR Director",
                            Role = "Admin",
                            Salary = 12000m,
                            Status = "Active"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
